name: CI Pipeline

on: [push, pull_request]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm test -- --coverage
      - name: Coverage check
        run: npx check-coverage --statements 80
      - name: SAST
        run: npx sonar-scanner # TODO: configurar token
      - name: Build artifact
        run: npm run build